#!/usr/bin/env python3
"""Pull the Excursion Check's decision code out of excursion.html so it can be
exercised in Node without a browser. The page keeps its logic inline, so this
slices the inline <script> from the first constant to the boot section and
wraps it with just enough DOM to run. Output is a CommonJS module for
tests/decisions.js; nothing ships it."""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
html = open(os.path.join(ROOT, 'excursion.html')).read()
js = '\n'.join(re.findall(r'<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>', html, re.S))
core = js[js.index('const WEATHER_API_KEY'):js.index('// ---- theme + boot ----')]

SHIM = '''// generated by scripts/extract-core.py — do not edit
const window = {}, navigator = { clipboard: null };
const els = {};
const el = (id) => els[id] || (els[id] = {
  checked: false, value: '', className: '', innerHTML: '', textContent: '', style: {},
  classList: { contains: () => false, add() {}, remove() {}, toggle() {} },
  querySelector() { return null; }, querySelectorAll() { return []; },
  setAttribute() {}, getAttribute() { return null; },
});
const document = { getElementById: el, querySelector: () => null, querySelectorAll: () => [], addEventListener() {} };
'''

EXPORTS = '''
module.exports = {
  decide, summarize, evidenceWeak, budgetUsed, budgetText, durationOk, transitHours, pastRating,
  maxDaysLate, hoursText, warmBands, coldBands, exposureHours, SHORT_ALLOWANCE_HOURS,
  zonedInstant, dayStart, dayEnd, coveredUntil, splitCovered, allowanceText, allowanceDays,
  drugLimits, ceilingUncertain, ceilingMargin, onDrugChange, els,
  PICKUP_HOUR, PACKOUT_RATING_HOURS, OBS_HOURS_GOOD, MAX_STATION_MILES,
  CEILING_MARGIN_F, CEILING_MARGIN_UNCERTAIN_F, PACK_MELT_F, ORIGIN_TZ,
  setDrug: (d) => { DRUGS = [d]; el('drug-select').value = '0'; },
  setPack: (p) => { packState = p; },
  setResult: (r) => { lastResult = r; },
  setFrozen: (b) => { el('product-frozen').checked = b; },
  setDates: (since, until) => { el('since').value = since || ''; el('until').value = until || ''; },
  verdict: () => {
    const v = el('verdict'), m = /class="verdict-big"[^>]*>([\\s\\S]*?)<\\/div>/.exec(v.innerHTML || '');
    return { cls: (v.className || '').replace('verdict-card ', '').trim(),
             big: m ? m[1].replace(/<[^>]+>/g, '').trim() : '',
             text: (v.innerHTML || '').replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').trim() };
  },
};
'''

out = os.path.join(ROOT, 'tests', '_core.generated.js')
open(out, 'w').write(SHIM + core + EXPORTS)
print('wrote', os.path.relpath(out, ROOT))
